name: branch

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/node@v1
      with:
        working-directory: web
    - uses: wtnb75/actions/eslint@v1
      with:
        working-directory: web
    - uses: wtnb75/actions/vitest@v1
      with:
        working-directory: web
