name: main

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/node@59135f92ed798e7963ac725ba850ad93a40f2639 # v1.0.5
      with:
        working-directory: web
    - uses: wtnb75/actions/eslint@59135f92ed798e7963ac725ba850ad93a40f2639 # v1.0.5
      with:
        working-directory: web
    - uses: wtnb75/actions/vitest@59135f92ed798e7963ac725ba850ad93a40f2639 # v1.0.5
      with:
        working-directory: web
    - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
    - name: download WASM sources
      run: task download
    - name: build WASM modules
      run: task build:wasm
    - name: build frontend
      run: pnpm run build
      working-directory: web
    - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        path: web/dist
    - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

  deploy:
    needs: build
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
